---
- name: Qurry ISS api with Ansible
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Make a call and registering the response
    uri:
      url: http://api.open-notify.org/iss-now.json
    register: astrojson

  - name: Display the contents
    debug: 
      var: astrojson["json"]
